# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import exam_service_pb2 as exam__service__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in exam_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ExamServiceStub(object):

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartExamSession = channel.unary_unary(
                '/exam_service.ExamService/StartExamSession',
                request_serializer=exam__service__pb2.StartExamRequest.SerializeToString,
                response_deserializer=exam__service__pb2.ExamSessionResponse.FromString,
                _registered_method=True)
        self.ReceiveTranscript = channel.unary_unary(
                '/exam_service.ExamService/ReceiveTranscript',
                request_serializer=exam__service__pb2.TranscriptRequest.SerializeToString,
                response_deserializer=exam__service__pb2.StandardResponse.FromString,
                _registered_method=True)
        self.SubmitAnswer = channel.unary_unary(
                '/exam_service.ExamService/SubmitAnswer',
                request_serializer=exam__service__pb2.AnswerRequest.SerializeToString,
                response_deserializer=exam__service__pb2.StandardResponse.FromString,
                _registered_method=True)
        self.GetCurrentState = channel.unary_unary(
                '/exam_service.ExamService/GetCurrentState',
                request_serializer=exam__service__pb2.SessionIdRequest.SerializeToString,
                response_deserializer=exam__service__pb2.ExamStateResponse.FromString,
                _registered_method=True)


class ExamServiceServicer(object):
    
    def StartExamSession(self, request, context):
        """1. Khởi tạo một phiên thi mới (Khi sinh viên bấm "Bắt đầu")
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReceiveTranscript(self, request, context):
        """2. Nhận kết quả Text từ Media Service (S2T) hoặc Coordinator gửi sang
        Dùng cho realtime: Student nói -> Text -> Exam Service xử lý
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitAnswer(self, request, context):
        """3. Nộp câu trả lời (dạng trắc nghiệm hoặc text nhập tay)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCurrentState(self, request, context):
        """4. Lấy trạng thái hiện tại (để check thời gian, trạm hiện tại)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExamServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartExamSession': grpc.unary_unary_rpc_method_handler(
                    servicer.StartExamSession,
                    request_deserializer=exam__service__pb2.StartExamRequest.FromString,
                    response_serializer=exam__service__pb2.ExamSessionResponse.SerializeToString,
            ),
            'ReceiveTranscript': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceiveTranscript,
                    request_deserializer=exam__service__pb2.TranscriptRequest.FromString,
                    response_serializer=exam__service__pb2.StandardResponse.SerializeToString,
            ),
            'SubmitAnswer': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitAnswer,
                    request_deserializer=exam__service__pb2.AnswerRequest.FromString,
                    response_serializer=exam__service__pb2.StandardResponse.SerializeToString,
            ),
            'GetCurrentState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCurrentState,
                    request_deserializer=exam__service__pb2.SessionIdRequest.FromString,
                    response_serializer=exam__service__pb2.ExamStateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'exam_service.ExamService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('exam_service.ExamService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ExamService(object):
    

    @staticmethod
    def StartExamSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exam_service.ExamService/StartExamSession',
            exam__service__pb2.StartExamRequest.SerializeToString,
            exam__service__pb2.ExamSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReceiveTranscript(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exam_service.ExamService/ReceiveTranscript',
            exam__service__pb2.TranscriptRequest.SerializeToString,
            exam__service__pb2.StandardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitAnswer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exam_service.ExamService/SubmitAnswer',
            exam__service__pb2.AnswerRequest.SerializeToString,
            exam__service__pb2.StandardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCurrentState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exam_service.ExamService/GetCurrentState',
            exam__service__pb2.SessionIdRequest.SerializeToString,
            exam__service__pb2.ExamStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
