# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: exam_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'exam_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x65xam_service.proto\x12\x0c\x65xam_service\">\n\x10StartExamRequest\x12\x12\n\nstudent_id\x18\x01 \x01(\t\x12\x16\n\x0e\x65xam_script_id\x18\x02 \x01(\t\"l\n\x13\x45xamSessionResponse\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x17\n\x0fstart_timestamp\x18\x03 \x01(\x03\x12\x18\n\x10\x64uration_seconds\x18\x04 \x01(\x05\"O\n\x11TranscriptRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x14\n\x0ctext_content\x18\x02 \x01(\t\x12\x10\n\x08is_final\x18\x03 \x01(\x08\"a\n\rAnswerRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x12\n\nstation_id\x18\x02 \x01(\t\x12\x13\n\x0bquestion_id\x18\x03 \x01(\t\x12\x13\n\x0b\x61nswer_data\x18\x04 \x01(\t\"4\n\x10StandardResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"&\n\x10SessionIdRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\"]\n\x11\x45xamStateResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x19\n\x11remaining_seconds\x18\x02 \x01(\x05\x12\x1d\n\x15\x63urrent_station_index\x18\x03 \x01(\x05\x32\xdb\x02\n\x0b\x45xamService\x12U\n\x10StartExamSession\x12\x1e.exam_service.StartExamRequest\x1a!.exam_service.ExamSessionResponse\x12T\n\x11ReceiveTranscript\x12\x1f.exam_service.TranscriptRequest\x1a\x1e.exam_service.StandardResponse\x12K\n\x0cSubmitAnswer\x12\x1b.exam_service.AnswerRequest\x1a\x1e.exam_service.StandardResponse\x12R\n\x0fGetCurrentState\x12\x1e.exam_service.SessionIdRequest\x1a\x1f.exam_service.ExamStateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'exam_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STARTEXAMREQUEST']._serialized_start=36
  _globals['_STARTEXAMREQUEST']._serialized_end=98
  _globals['_EXAMSESSIONRESPONSE']._serialized_start=100
  _globals['_EXAMSESSIONRESPONSE']._serialized_end=208
  _globals['_TRANSCRIPTREQUEST']._serialized_start=210
  _globals['_TRANSCRIPTREQUEST']._serialized_end=289
  _globals['_ANSWERREQUEST']._serialized_start=291
  _globals['_ANSWERREQUEST']._serialized_end=388
  _globals['_STANDARDRESPONSE']._serialized_start=390
  _globals['_STANDARDRESPONSE']._serialized_end=442
  _globals['_SESSIONIDREQUEST']._serialized_start=444
  _globals['_SESSIONIDREQUEST']._serialized_end=482
  _globals['_EXAMSTATERESPONSE']._serialized_start=484
  _globals['_EXAMSTATERESPONSE']._serialized_end=577
  _globals['_EXAMSERVICE']._serialized_start=580
  _globals['_EXAMSERVICE']._serialized_end=927
# @@protoc_insertion_point(module_scope)
